version: '3.8'

services:
  web:
    build: .
    restart: always
    command: python3 leitor_projeto/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=leitor_projeto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=leitor_db
    depends_on:
      - leitor_db
    
  leitor_db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leitor_projeto

volumes:
  postgres_data: