# Generated by Django 5.2.3 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosimagem',
            name='imagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.imagemupload'),
        ),
    ]
