# Generated by Django 5.2.3 on 2025-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_dadosimagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
    ]
