# Generated by Django 5.2.3 on 2025-06-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_usuario_perfil_user_alter_perfil_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosimagem',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
