# Generated by Django 5.2.3 on 2025-06-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_dadosimagem_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
