# Generated by Django 5.2.3 on 2025-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_perfil_bio_alter_perfil_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemupload',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
